export const expeditionOptions = [
  { value: 'pos', label: 'POS Indonesia' },
  { value: 'lion', label: 'Lion Parcel' },
  { value: 'ninja', label: 'Ninja Xpress' },
  { value: 'ide', label: 'ID Express' },
  { value: 'sicepat', label: 'SiCepat Express' },
  { value: 'sap', label: 'SAP Express' },
  { value: 'ncs', label: 'Nusantara Card Semesta' },
  { value: 'anteraja', label: 'AnterAja' },
  { value: 'rex', label: 'Rol Express Indonesia' },
  { value: 'jtl', label: 'JTL Express' },
  { value: 'sentral', label: 'Sentral Cargo' },
  { value: 'jne', label: 'Jalur Nugraha Ekakurir' },
  { value: 'tiki', label: 'Citra Van Titipan Kilat' },
  { value: 'rpx', label: 'RPX Holding' },
  { value: 'pandu', label: 'Pandu Logistics' },
  { value: 'wahana', label: 'Wahana Prestasi Logistik' },
  { value: 'jnt', label: 'J&T Express' },
  { value: 'pahala', label: 'Pahala Kencana Express' },
  { value: 'slis', label: 'Solusi Ekspres' },
  { value: 'expedito', label: 'Expedito' },
  { value: 'ray', label: 'Rayspeed' },
  { value: 'dse', label: '21 Express' },
  { value: 'first', label: 'First Logistics' },
  { value: 'star', label: 'Star Cargo' },
  { value: 'idl', label: 'IDL Cargo' },
];
